files:
  - source: /po/common/common.pot
    translation: /po/common/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        pt-PT: pt_PT
        zh-CN: zh_CN
        zh-HK: zh_HK
        en-GB: en_GB
        en-AU: en_AU
        nl-BE: nl_BE
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /po/openbeautyfacts/openbeautyfacts.pot
    translation: /po/openbeautyfacts/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        en-AU: en_AU
        zh-CN: zh_CN
        zh-HK: zh_HK
        nl-BE: nl_BE
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /po/openfoodfacts/openfoodfacts.pot
    translation: /po/openfoodfacts/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        nl-BE: nl_BE
        nl: nl_NL
        pt-BR: pt_BR
        pt-PT: pt_PT
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /po/openpetfoodfacts/openpetfoodfacts.pot
    translation: /po/openpetfoodfacts/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /po/tags/tags.pot
    translation: /po/tags/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/a-propos.html
    translation: /lang/%two_letters_code%/a-propos.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/additifs.html
    translation: /lang/%two_letters_code%/additifs.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/code-of-conduct.html
    translation: /lang/%two_letters_code%/code-of-conduct.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/comment-ajouter-un-produit.html
    translation: /lang/%two_letters_code%/comment-ajouter-un-produit.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/conditionnements.html
    translation: /lang/%two_letters_code%/conditionnements.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/conditions-d-utilisation.html
    translation: /lang/%two_letters_code%/conditions-d-utilisation.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/contact.en.html
    translation: /lang/%two_letters_code%/contact.en.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/contact.html
    translation: /lang/%two_letters_code%/contact.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/contribute.html
    translation: /lang/%two_letters_code%/
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/data.en.html
    translation: /lang/%two_letters_code%/data.en.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/data.html
    translation: /lang/%two_letters_code%/data.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/discover.html
    translation: /lang/%two_letters_code%/discover.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/faq.html
    translation: /lang/%two_letters_code%/faq.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/feuille-de-route-2012.html
    translation: /lang/%two_letters_code%/feuille-de-route-2012.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/how-to-add-a-product.html
    translation: /lang/%two_letters_code%/how-to-add-a-product.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/index.en.html
    translation: /lang/%two_letters_code%/index.en.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/index.foundation.en.html
    translation: /lang/%two_letters_code%/index.foundation.en.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/index.html
    translation: /lang/%two_letters_code%/index.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/legal.html
    translation: /lang/%two_letters_code%/legal.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/marques.html
    translation: /lang/%two_letters_code%/marques.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/mentions-legales.html
    translation: /lang/%two_letters_code%/mentions-legales.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/missions.html
    translation: /lang/%two_letters_code%/missions.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/mode-d-emploi.html
    translation: /lang/%two_letters_code%/mode-d-emploi.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/nutrition-score-uk.html
    translation: /lang/%two_letters_code%/nutrition-score-uk.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/open-food-hunt-2015.html
    translation: /lang/%two_letters_code%/open-food-hunt-2015.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/origines.html
    translation: /lang/%two_letters_code%/origines.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/press-and-blogs.html
    translation: /lang/%two_letters_code%/press-and-blogs.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/press.html
    translation: /lang/%two_letters_code%/press.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/products.html
    translation: /lang/%two_letters_code%/products.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/sugar.html
    translation: /lang/%two_letters_code%/sugar.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/terms-of-use.html
    translation: /lang/%two_letters_code%/terms-of-use.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/users.html
    translation: /lang/%two_letters_code%/users.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/utilisateurs.html
    translation: /lang/%two_letters_code%/utilisateurs.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

  - source: /lang/en/who-we-are.html
    translation: /lang/%two_letters_code%/who-we-are.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr

