files:
  - source: /po/common/common.pot
    translation: /po/common/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        pt-PT: pt_PT
        zh-CN: zh_CN
        zh-HK: zh_HK
        en-GB: en_GB
        en-AU: en_AU
        nl-BE: nl_BE
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /po/openbeautyfacts/openbeautyfacts.pot
    translation: /po/openbeautyfacts/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        en-AU: en_AU
        zh-CN: zh_CN
        zh-HK: zh_HK
        nl-BE: nl_BE
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /po/openfoodfacts/openfoodfacts.pot
    translation: /po/openfoodfacts/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        nl-BE: nl_BE
        nl: nl_NL
        pt-BR: pt_BR
        pt-PT: pt_PT
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /po/openpetfoodfacts/openpetfoodfacts.pot
    translation: /po/openpetfoodfacts/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /po/tags/tags.pot
    translation: /po/tags/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/a-propos.html
    translation: /lang/%two_letters_code%/texts/a-propos.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/additifs.html
    translation: /lang/%two_letters_code%/texts/additifs.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/code-of-conduct.html
    translation: /lang/%two_letters_code%/texts/code-of-conduct.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/comment-ajouter-un-produit.html
    translation: /lang/%two_letters_code%/texts/comment-ajouter-un-produit.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/conditionnements.html
    translation: /lang/%two_letters_code%/texts/conditionnements.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/conditions-d-utilisation.html
    translation: /lang/%two_letters_code%/texts/conditions-d-utilisation.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/contact.en.html
    translation: /lang/%two_letters_code%/texts/contact.en.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/contact.html
    translation: /lang/%two_letters_code%/texts/contact.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/contribute.html
    translation: /lang/%two_letters_code%/texts/contribute.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/data.en.html
    translation: /lang/%two_letters_code%/texts/data.en.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/data.html
    translation: /lang/%two_letters_code%/texts/data.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/discover.html
    translation: /lang/%two_letters_code%/texts/discover.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/faq.html
    translation: /lang/%two_letters_code%/texts/faq.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/feuille-de-route-2012.html
    translation: /lang/%two_letters_code%/texts/feuille-de-route-2012.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/how-to-add-a-product.html
    translation: /lang/%two_letters_code%/texts/how-to-add-a-product.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/index.en.html
    translation: /lang/%two_letters_code%/texts/index.en.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/index.foundation.en.html
    translation: /lang/%two_letters_code%/texts/index.foundation.en.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/index.html
    translation: /lang/%two_letters_code%/texts/index.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/legal.html
    translation: /lang/%two_letters_code%/texts/legal.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/marques.html
    translation: /lang/%two_letters_code%/texts/marques.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/mentions-legales.html
    translation: /lang/%two_letters_code%/texts/mentions-legales.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/missions.html
    translation: /lang/%two_letters_code%/texts/missions.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/mode-d-emploi.html
    translation: /lang/%two_letters_code%/texts/mode-d-emploi.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/nutrition-score-uk.html
    translation: /lang/%two_letters_code%/texts/nutrition-score-uk.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/open-food-hunt-2015.html
    translation: /lang/%two_letters_code%/texts/open-food-hunt-2015.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/origines.html
    translation: /lang/%two_letters_code%/texts/origines.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/press-and-blogs.html
    translation: /lang/%two_letters_code%/texts/press-and-blogs.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/press.html
    translation: /lang/%two_letters_code%/texts/press.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/products.html
    translation: /lang/%two_letters_code%/texts/products.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/sugar.html
    translation: /lang/%two_letters_code%/texts/sugar.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/terms-of-use.html
    translation: /lang/%two_letters_code%/texts/terms-of-use.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/users.html
    translation: /lang/%two_letters_code%/texts/users.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/utilisateurs.html
    translation: /lang/%two_letters_code%/texts/utilisateurs.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
  - source: /lang/en/texts/who-we-are.html
    translation: /lang/%two_letters_code%/texts/who-we-are.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr
