version: "3.7"
services:
  memcached:
    image: memcached:1.6-alpine
    networks:
      - webnet
  postgres:
    image: postgres:12-alpine
    networks:
      - webnet
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=minion
  backend:
    image: ghcr.io/openfoodfacts/openfoodfacts-server/backend:${TAG}
    environment:
      - PRODUCERS_PLATFORM
      - PRODUCT_OPENER_DOMAIN
      - PRODUCT_OPENER_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - ROBOTOFF_URL
      - GOOGLE_CLOUD_VISION_API_KEY
      - CROWDIN_PROJECT_IDENTIFIER
      - CROWDIN_PROJECT_KEY
      - GEOLITE2_PATH
    depends_on:
      - memcached
      - postgres
    volumes:
      - ./logs/apache2:/var/log/apache2
      - ./logs/apache2:/mnt/podata/logs
      - ./logs/apache2:/var/log/httpd
      - ./conf/apache.conf:/etc/apache2/sites-enabled/product-opener.conf
      - type: tmpfs
        target: /mnt/podata/mnt
    command: ["/bin/sh", "/opt/product-opener/scripts/po-foreground.sh"]
    networks:
      - webnet
  frontend:
    image: ghcr.io/openfoodfacts/openfoodfacts-server/frontend:${TAG}
    depends_on:
      - backend
    environment:
      - PRODUCT_OPENER_DOMAIN
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${PRODUCT_OPENER_PORT}:80
    networks:
      - webnet
networks:
  webnet:
volumes:
  dbdata:
  pgdata:
  podata:
  product_images:
  html_data:
