version: "3.7"
services:
  backend:
    image: openfoodfacts-server/backend:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: runnable
    volumes:
      - ./:/opt/product-opener/
  frontend:
    image: nginx:stable-alpine
    volumes:
      - ./:/opt/product-opener/
