version: "3.7"
services:
  backend:
    image: openfoodfacts-server/backend:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: runnable
    volumes:
      - ./:/opt/product-opener # we don't COPY the files in the Dockerfile 'runnable' target, so we have to bind them
      - icons_dist:/opt/product-opener/html/images/icons/dist:ro
      - js_dist:/opt/product-opener/html/js/dist:ro
      - css_dist:/opt/product-opener/html/css/dist:ro
      - image_attributes:/opt/product-opener/html/images/attributes:ro
      - node_modules:/opt/product-opener/node_modules:ro
  frontend:
    image: openfoodfacts-server/frontend:dev
    build:
      context: .
      dockerfile: Dockerfile.frontend
  mongodb:
    image: mongo:4.4
    networks:
      - webnet
