version: "3.7"
services:
  backend:
    volumes:
      - type: bind
        source: ./backend-dev/conf/Config2.pm
        target: /opt/product-opener/lib/ProductOpener/Config2.pm
      - type: bind
        source: ./backend-dev/scripts/
        target: /opt/scripts/
      - ./logs/apache2:/var/log/apache2
      - ./logs/apache2:/mnt/podata/logs
      - ./logs/apache2:/var/log/httpd
      - ./logs/nginx:/var/log/nginx
