version: "3.7"
services:
  frontend:
    volumes:
      - /mnt/data/:/opt/product-opener/html/data # Data mount for Robotoff static dumps
      - product_images:/opt/product-opener/html/images/products
      - html_data:/opt/product-opener/html/data

  backend:
    volumes:
      - podata:/mnt/podata
      - product_images:/opt/product-opener/html/images/products
      - html_data:/opt/product-opener/html/data

  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  podata:
  product_images:
  html_data:
