version: "3.7"
services:
  backend:
    image: openfoodfacts-server/backend:prod
    build:
      context: .
      dockerfile: Dockerfile
  frontend:
    image: openfoodfacts-server/frontend:prod
    build:
      context: .
      dockerfile: Dockerfile.frontend
volumes:
  product_images:
    external: true
  html_data:
    external: true
  icons_dist:
    external: true
  js_dist:
    external: true
  css_dist: 
    external: true
  image_attributes:
    external: true
  node_modules:
    external: true
  users:
    external: true
  products:
    external: true
