version: "3.7"
services:
  frontend:
    volumes:
      # Data mount for Robotoff static data dumps:
      # - openfoodfacts-products.jsonl.gz
      # - categories.full.json
      # - ingredients.full.json
      # - labels.full.json
      # - brands.full.json
      - type: bind
        source: /mnt/data/
        target: /opt/product-opener/html/data
