name: Container Image Build CI

on:
  push:
    branches:
      - main
      - deploy-*
    tags: 
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name: [
          "frontend",
          "backend"
        ]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.6.0
        buildkitd-flags: --debug

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ github.repository }}/${{ matrix.image_name }}
        file: ${{ matrix.image_name == 'frontend' && 'Dockerfile.frontend' || 'Dockerfile' }}
        tags: |
          type=semver,pattern={{version}}
          type=ref,event=pr
          type=ref,event=branch
          type=sha,format=long

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
