name: "Daily tasks (cronjobs)"

on:
  push:
    branches: [sync-dev-db]
  schedule:
  - cron: "0 0 * * *" # once a day at 00:00

jobs:
  # TODO: Uncomment when prod environment is ready
  # prod-db-backup:
  #   runs-on: ubuntu-latest
  #   environment: off-org
  #   concurrency: off-org
  #   steps:
  #   - name: Backup production database
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       proxy_host: ${{ secrets.PROXY_HOST }}
  #       proxy_username: ${{ secrets.USERNAME }}
  #       proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       script_stop: false
  #       script: |
  #         cd openfoodfacts-server/
  #         sudo sh ./scripts/mongodb_dump.sh /mnt/data/ openfoodfacts localhost off

  dev-db-sync:
    runs-on: ubuntu-latest
    environment: off-net
    concurrency: off-net
    steps:
    - name: Sync prod db data to dev MongoDB
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.USERNAME }}
        proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: false
        script: |
          cd openfoodfacts-server/
          wget https://static.openfoodfacts.org/data/openfoodfacts-mongodbdump.tar.gz
          sudo docker cp openfoodfacts-mongodbdump.tar.gz po_mongodb_1:/data/db
          sudo docker-compose exec mongodb /bin/sh -c "cd /data/db && tar -xzvf openfoodfacts-mongodbdump.tar.gz && mongorestore"
