name: Container Image Deployment CI

on:
  push:
    branches:
      - main
      - deploy-*
    tags: 
      - v*.*.*

steps:
  integration:
    - name: Wait for deploy workflow
      uses: tomchv/wait-my-workflow@v1.1.0
      id: wait-build
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: deploy
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        intervalSeconds: 10
        timeoutSeconds: 600 # 10m
